name: example
description: A project that showcases usage of swagger_parser
publish_to: none
environment:
  sdk: 3.5.4

dependencies:
  dart_mappable: ^4.2.2
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  carapacik_lints: ^1.9.1
  custom_lint: ^0.6.8
  dart_mappable_builder: ^4.2.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  swagger_parser:
    path:
      ../
