name: example
description: A project that showcases usage of swagger_parser
publish_to: none
environment:
  sdk: ^3.8.0

dependencies:
  dart_mappable: ^4.2.2
  dio: ^5.7.0
  faker: ^2.2.0
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mockito: ^5.4.4
  retrofit: ^4.4.1
  riverpod_annotation: ^2.6.1

  riverpod: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  carapacik_lints: ^1.9.1
  custom_lint: ^0.6.8
  dart_mappable_builder: ^4.2.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  swagger_parser:
    path: ../
  build_runner: ^2.4.14
