include: package:carapacik_lints/core.yaml
analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
    always_put_control_body_on_new_line: ignore
  exclude:
    - 'test/e2e/tests/**'
linter:
  rules:
    always_use_package_imports: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    prefer_relative_imports: true
