name: swagger_parser
description: Package that generates REST clients and data classes from OpenApi definition file
version: 1.20.0
repository: https://github.com/Carapacik/swagger_parser/tree/main/swagger_parser
topics:
  - swagger
  - openapi
  - codegen
  - api
  - rest
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  args: ^2.6.0
  collection: ^1.19.1
  meta: ^1.16.0
  path: ^1.9.1
  yaml: ^3.1.2

dev_dependencies:
  carapacik_lints: ^1.9.2
  test: ^1.25.11
